

CREATE TABLE `event` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EVENTNAME` varchar(255) NOT NULL,
  `PRICE` double NOT NULL,
  `EVENTTYPE` varchar(255) NOT NULL,
  `EVENTTOWHOM` varchar(255) NOT NULL,
  `STARTEVENTDATE` date NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8$$

